/**
 * Consolidated exports for all Ripple service types
 * Organized by domain for easy importing
 */

// Authentication types
export type {
  RippleAuthConfig,
  RippleEnvironment,
  RippleTokenRequest,
  RippleTokenResponse,
  RippleTokenIntrospection,
  StoredRippleToken,
  RippleAuthError,
  RippleEnvironmentConfig,
  RippleScope,
  RippleAuthState
} from './auth';

// Payment types
export type {
  RipplePaymentV4,
  PaymentStatus,
  PaymentType,
  MoneyAmount,
  RippleQuoteV4,
  QuoteRequest,
  QuoteCollection,
  CreatePaymentRequest,
  CreateOrchestrationPaymentRequest,
  IdentityDetails,
  Address,
  PaymentMethod,
  ODLPayment,
  ODLQuote,
  CrossBorderPayment,
  PaymentCorridor,
  ComplianceCheck,
  PaymentNotification,
  PaymentEventType,
  PaymentError,
  PaymentListResponse,
  PaymentResponse,
  PaymentFilters,
  PaymentSearchParams
} from './payments';

// Custody types
export type {
  CustodyWallet,
  WalletType,
  CustodyNetwork,
  WalletStatus,
  SecurityLevel,
  CustodyAsset,
  AssetType,
  AssetBalance,
  CustodyTransaction,
  TransactionType,
  TransactionStatus,
  MultiSigWallet,
  MultiSigSigner,
  SignerRole,
  MultiSigProposal,
  ProposalType,
  ProposalStatus,
  ProposalSignature,
  CustodyKey,
  KeyType,
  KeyStatus,
  KeyRotationPolicy,
  CreateWalletRequest,
  TransferRequest,
  TransactionPriority,
  SignTransactionRequest,
  WalletListResponse,
  AssetListResponse,
  TransactionListResponse,
  CustodyAuditLog,
  AuditAction,
  CustodyConfig,
  TransactionLimits,
  AutoSweepConfig,
  ComplianceRule,
  ComplianceRuleType,
  ComplianceAction,
  CustodyError,
  WalletFilters,
  TransactionFilters
} from './custody';

// Stablecoin types
export type {
  RLUSDToken,
  StablecoinNetwork,
  XRPLTrustLine,
  CreateTrustLineRequest,
  TrustLineFlags,
  ERC20TokenInfo,
  ERC20Allowance,
  ERC20TransferEvent,
  BridgeTransaction,
  BridgeStatus,
  BridgeQuote,
  StablecoinTransaction,
  StablecoinTransactionType,
  StablecoinTransactionStatus,
  StablecoinBalance,
  StablecoinAccount,
  AccountRiskLevel,
  MintRequest,
  BurnRequest,
  BankAccountInfo,
  RedemptionRequest,
  RedemptionStatus,
  WireTransferDetails,
  ComplianceCheckType,
  ComplianceStatus,
  ComplianceFlag,
  StablecoinPrice,
  PriceOracle,
  TransferRequest as StablecoinTransferRequest,
  ApproveRequest,
  BridgeRequest,
  TransactionListResponse as StablecoinTransactionListResponse,
  BalanceResponse,
  BridgeQuoteResponse,
  BridgeRoute,
  StablecoinConfig,
  NetworkConfig as StablecoinNetworkConfig,
  GasLimits,
  BridgeConfig,
  ComplianceConfig,
  RedemptionConfig,
  StablecoinError,
  TransactionFilters as StablecoinTransactionFilters,
  BridgeFilters,
  StablecoinAnalytics,
  NetworkAnalytics
} from './stablecoin';

// Identity types
export type {
  RippleIdentity,
  IdentityType,
  IdentityStatus,
  VerificationLevel,
  RiskLevel as IdentityRiskLevel,
  IndividualIdentity,
  PersonalInfo,
  Gender,
  MaritalStatus,
  ContactInfo as IdentityContactInfo,
  ContactMethod,
  AddressInfo,
  AddressType,
  BusinessIdentity,
  BusinessInfo,
  EmployeeRange,
  RevenueRange,
  LegalStructure,
  BusinessType,
  RegulatoryLicense,
  RegistrationInfo,
  BeneficialOwner,
  AuthorizedSigner,
  SigningAuthority,
  IdentityDocument,
  DocumentType as IdentityDocumentType,
  DocumentCategory,
  DocumentStatus,
  EmploymentInfo,
  EmploymentStatus,
  IncomeSource,
  FinancialInfo,
  CryptoExperience,
  InvestmentObjective,
  RiskTolerance,
  BusinessFinancialInfo,
  FundingSource,
  BankAccountDetails,
  BankAccountType,
  TransactionVolume,
  VolumeRange,
  TransactionSizeRange,
  TransactionPurpose,
  SourceOfFunds,
  FundSource,
  FundSourceType,
  VerificationStatus as IdentityVerificationStatus,
  VerificationCheck,
  VerificationCheckType,
  VerificationCheckStatus,
  CheckResult,
  PEPCheck,
  PEPLevel,
  PoliticalPosition,
  PEPRelation,
  RelationType,
  CreateIdentityRequest,
  UpdateIdentityRequest,
  SubmitVerificationRequest,
  DocumentUpload,
  IdentityListResponse,
  VerificationResponse,
  IdentityFilters,
  IdentitySearchParams,
  IdentityConfig,
  VerificationConfig,
  IdentityComplianceConfig,
  PEPAcceptancePolicy,
  DocumentConfig,
  RiskConfig,
  RiskFactor as IdentityRiskFactor,
  ScoringModel,
  RiskThresholds,
  IdentityAnalytics,
  VerificationTrend
} from './identity';

// Common types
export type {
  RippleApiResponse,
  RippleApiError,
  ResponseMeta,
  PaginationParams,
  PaginatedResponse,
  Currency,
  Money,
  RippleNetwork,
  NetworkConfig as CommonNetworkConfig,
  AuditTrail,
  EntityStatus,
  VerificationStatus as CommonVerificationStatus,
  StandardAddress,
  ContactInfo as CommonContactInfo,
  DocumentReference,
  DocumentType as CommonDocumentType,
  ValidationError,
  ValidationResult,
  ServiceResult,
  ServiceError,
  ErrorCategory,
  WebhookPayload,
  WebhookSubscription,
  WebhookRetryConfig,
  TimeRange,
  BusinessHours,
  RiskProfile,
  RiskLevel as CommonRiskLevel,
  RiskFactor as CommonRiskFactor,
  FeatureFlag,
  CacheConfig,
  CachedItem,
  Metric,
  AnalyticsEvent,
  ServiceConfig,
  RateLimitConfig,
  HealthStatus,
  HealthCheck
} from './common';


// Oracle types
export type {
  PriceDataPoint,
  OracleSetParams,
  XRPLPriceOracle,
  XRPLOraclePriceData,
  XRPLOracleUpdate,
  OracleSetResult,
  OracleDeleteResult,
  OracleDetails,
  AccountOracleSummary,
  CreateOracleRequest,
  UpdatePricesRequest,
  OracleAnalytics,
  OracleSubscription,
  OracleErrorType,
  OracleError
} from './oracle';
