SELECT
  t.id AS token_id,
  t.name,
  t.symbol,
  t.decimals,
  t.standard,
  t.total_supply,
  t.metadata,
  t.status,
  t.description,
  t.created_at AS token_created_at,
  t.updated_at AS token_updated_at,
  p.id AS erc3525_property_id,
  p.value_decimals,
  p.base_uri,
  p.metadata_storage,
  p.slot_type,
  p.is_burnable,
  p.is_pausable,
  p.has_royalty,
  p.royalty_percentage,
  p.royalty_receiver,
  p.slot_approvals,
  p.value_approvals,
  p.updatable_uris,
  p.updatable_slots,
  p.value_transfers_enabled,
  p.sales_config,
  p.mergable,
  p.splittable,
  p.slot_transfer_validation,
  p.dynamic_metadata,
  p.allows_slot_enumeration,
  p.value_aggregation,
  p.permissioning_enabled,
  p.supply_tracking,
  p.updatable_values,
  p.custom_extensions,
  p.fractionalizable,
  p.fractional_ownership_enabled,
  p.auto_unit_calculation,
  p.custom_slot_properties,
  p.slot_enumeration_enabled,
  p.value_aggregation_enabled,
  p.permissioning_advanced,
  p.slot_transfer_restrictions,
  p.value_transfer_restrictions,
  p.financial_instrument_type,
  p.principal_amount,
  p.interest_rate,
  p.maturity_date,
  p.coupon_frequency,
  p.payment_schedule,
  p.early_redemption_enabled,
  p.redemption_penalty_rate,
  p.derivative_type,
  p.underlying_asset,
  p.underlying_asset_address,
  p.strike_price,
  p.expiration_date,
  p.settlement_type,
  p.margin_requirements,
  p.leverage_ratio,
  p.compliance_module_address,
  p.policy_engine_address,
  p.vesting_module_address,
  p.document_module_address,
  p.slot_approvable_module_address,
  p.slot_manager_module_address,
  p.value_exchange_module_address,
  p.initial_owner,
  p.value_exchange_config,
  p.slot_manager_config,
  p.slot_approvable_config,
  p.document_config,
  p.compliance_config,
  p.policy_engine_config,
  p.whitelist_config,
  p.metadata AS property_metadata,
  p.created_at AS property_created_at,
  p.updated_at AS property_updated_at
FROM
  (
    tokens t
    LEFT JOIN token_erc3525_properties p ON ((t.id = p.token_id))
  )
WHERE
  (t.standard = 'ERC-3525' :: token_standard_enum);