SELECT
  t.id AS token_id,
  t.name,
  t.symbol,
  t.decimals,
  t.standard,
  t.total_supply,
  t.metadata,
  t.status,
  t.description,
  t.created_at AS token_created_at,
  t.updated_at AS token_updated_at,
  p.id AS erc1400_property_id,
  p.initial_supply,
  p.cap,
  p.is_mintable,
  p.is_burnable,
  p.is_pausable,
  p.document_uri,
  p.document_hash,
  p.controller_address,
  p.require_kyc,
  p.security_type,
  p.issuing_jurisdiction,
  p.issuing_entity_name,
  p.issuing_entity_lei,
  p.transfer_restrictions,
  p.kyc_settings,
  p.compliance_settings,
  p.forced_transfers,
  p.issuance_modules,
  p.document_management,
  p.recovery_mechanism,
  p.regulation_type,
  p.is_multi_class,
  p.tranche_transferability,
  p.token_details,
  p.legal_terms,
  p.prospectus,
  p.enforce_kyc,
  p.forced_redemption_enabled,
  p.whitelist_enabled,
  p.holding_period,
  p.max_investor_count,
  p.investor_accreditation,
  p.auto_compliance,
  p.manual_approvals,
  p.compliance_module,
  p.is_issuable,
  p.granular_control,
  p.dividend_distribution,
  p.corporate_actions,
  p.custom_features,
  p.geographic_restrictions,
  p.compliance_automation_level,
  p.institutional_grade,
  p.custody_integration_enabled,
  p.prime_brokerage_support,
  p.settlement_integration,
  p.real_time_compliance_monitoring,
  p.automated_sanctions_screening,
  p.aml_monitoring_enabled,
  p.advanced_corporate_actions,
  p.stock_splits_enabled,
  p.treasury_management_enabled,
  p.advanced_governance_enabled,
  p.proxy_voting_enabled,
  p.cross_border_trading_enabled,
  p.multi_jurisdiction_compliance,
  p.enhanced_reporting_enabled,
  p.beneficial_ownership_tracking,
  p.traditional_finance_integration,
  p.swift_integration_enabled,
  p.iso20022_messaging_support,
  p.advanced_risk_management,
  p.insurance_coverage_enabled,
  p.created_at AS property_created_at,
  p.updated_at AS property_updated_at
FROM
  (
    tokens t
    LEFT JOIN token_erc1400_properties p ON ((t.id = p.token_id))
  )
WHERE
  (t.standard = 'ERC-1400' :: token_standard_enum);