SELECT
  t.id AS token_id,
  t.name,
  t.symbol,
  t.decimals,
  t.standard,
  t.total_supply,
  t.metadata,
  t.status,
  t.description,
  t.created_at AS token_created_at,
  t.updated_at AS token_updated_at,
  p.id AS erc3525_property_id,
  p.value_decimals,
  p.base_uri,
  p.metadata_storage,
  p.slot_type,
  p.is_burnable,
  p.is_pausable,
  p.has_royalty,
  p.royalty_percentage,
  p.royalty_receiver,
  p.slot_approvals,
  p.value_approvals,
  p.access_control,
  p.updatable_uris,
  p.updatable_slots,
  p.value_transfers_enabled,
  p.sales_config,
  p.mergable,
  p.splittable,
  p.slot_transfer_validation,
  p.dynamic_metadata,
  p.allows_slot_enumeration,
  p.value_aggregation,
  p.permissioning_enabled,
  p.supply_tracking,
  p.updatable_values,
  p.fractional_ownership_enabled,
  p.financial_instrument_type,
  p.principal_amount,
  p.interest_rate,
  p.maturity_date,
  p.coupon_frequency,
  p.early_redemption_enabled,
  p.derivative_type,
  p.underlying_asset,
  p.strike_price,
  p.expiration_date,
  p.settlement_type,
  p.slot_creation_enabled,
  p.dynamic_slot_creation,
  p.cross_slot_transfers,
  p.value_computation_method,
  p.accrual_enabled,
  p.accrual_rate,
  p.partial_value_trading,
  p.minimum_trade_value,
  p.yield_farming_enabled,
  p.liquidity_provision_enabled,
  p.compound_interest_enabled,
  p.flash_loan_enabled,
  p.regulatory_compliance_enabled,
  p.kyc_required,
  p.accredited_investor_only,
  p.created_at AS property_created_at,
  p.updated_at AS property_updated_at
FROM
  (
    tokens t
    LEFT JOIN token_erc3525_properties p ON ((t.id = p.token_id))
  )
WHERE
  (t.standard = 'ERC-3525' :: token_standard_enum);