SELECT
  t.id AS token_id,
  t.name,
  t.symbol,
  t.decimals,
  t.standard,
  t.total_supply,
  t.metadata,
  t.status,
  t.description,
  t.created_at AS token_created_at,
  t.updated_at AS token_updated_at,
  p.id AS erc4626_property_id,
  p.asset_address,
  p.asset_name,
  p.asset_symbol,
  p.asset_decimals,
  p.vault_type,
  p.is_mintable,
  p.is_burnable,
  p.is_pausable,
  p.vault_strategy,
  p.custom_strategy,
  p.strategy_controller,
  p.access_control,
  p.permit,
  p.flash_loans,
  p.emergency_shutdown,
  p.fee_structure,
  p.rebalancing_rules,
  p.performance_metrics,
  p.yield_source,
  p.automated_rebalancing,
  p.strategy_complexity,
  p.multi_asset_enabled,
  p.rebalancing_enabled,
  p.auto_compounding_enabled,
  p.yield_optimization_enabled,
  p.risk_management_enabled,
  p.risk_tolerance,
  p.apy_tracking_enabled,
  p.benchmark_tracking_enabled,
  p.benchmark_index,
  p.compound_frequency,
  p.governance_token_enabled,
  p.strategy_voting_enabled,
  p.fee_voting_enabled,
  p.insurance_enabled,
  p.emergency_exit_enabled,
  p.circuit_breaker_enabled,
  p.liquidity_mining_enabled,
  p.market_making_enabled,
  p.cross_chain_yield_enabled,
  p.institutional_grade,
  p.compliance_reporting_enabled,
  p.third_party_audits_enabled,
  p.created_at AS property_created_at,
  p.updated_at AS property_updated_at
FROM
  (
    tokens t
    LEFT JOIN token_erc4626_properties p ON ((t.id = p.token_id))
  )
WHERE
  (t.standard = 'ERC-4626' :: token_standard_enum);