SELECT
  t.id AS token_id,
  t.name,
  t.symbol,
  t.decimals,
  t.standard,
  t.total_supply,
  t.metadata,
  t.status,
  t.description,
  t.created_at AS token_created_at,
  t.updated_at AS token_updated_at,
  p.id AS erc1155_property_id,
  p.base_uri,
  p.metadata_storage,
  p.has_royalty,
  p.royalty_percentage,
  p.royalty_receiver,
  p.is_burnable,
  p.is_pausable,
  p.access_control,
  p.updatable_uris,
  p.supply_tracking,
  p.enable_approval_for_all,
  p.sales_config,
  p.whitelist_config,
  p.batch_transfer_limits,
  p.dynamic_uri_config,
  p.batch_minting_config,
  p.transfer_restrictions,
  p.container_config,
  p.lazy_minting_enabled,
  p.burning_enabled,
  p.updatable_metadata,
  p.crafting_enabled,
  p.fusion_enabled,
  p.experience_points_enabled,
  p.voting_power_enabled,
  p.marketplace_fees_enabled,
  p.bridge_enabled,
  p.pricing_model,
  p.base_price,
  p.bulk_discount_enabled,
  p.airdrop_enabled,
  p.claim_period_enabled,
  p.claim_start_time,
  p.claim_end_time,
  p.created_at AS property_created_at,
  p.updated_at AS property_updated_at
FROM
  (
    tokens t
    LEFT JOIN token_erc1155_properties p ON ((t.id = p.token_id))
  )
WHERE
  (t.standard = 'ERC-1155' :: token_standard_enum);